import random
print("\n\t\t******** *********\n \t\tPassword Generator\n\t\t******** *********\nby Sandeep Benny")
print("\n A simple password generator.\nThis is generated by the python Random Module.\n")
lowercase="abcdefghijklmnopqrstuvwyxyz"
uppercase=lowercase.upper()
number="0123456789"
symbols="!@#$%^&*()+=-~`.,?/';\"\;"
use_for = uppercase+lowercase+symbols+number
#length_for_pass=input("value\n")
length_for_pass=int(input("Enter the Length of the password to process?: \n "))
#length_for_pass1=10#
password="".join(random.sample(use_for,length_for_pass))
print("Generated PAss:",password)
                 